CREATE TABLE sc_party (
   SC_PIN_ID INT,
   SC_ROLE_ID INT,
   INDEX CHAR (5),
   NAME TEXT,
   CREATED_DT TIMESTAMP,
   CREATED_BY INT,
   MODIF_DT TIMESTAMP,
   MODIF_BY INT,
   MARITAL_ID INT,
   SC_TEN_ID INT,
   RECNO INT PRIMARY KEY
);